### PR TITLE
A better 403 error fix.

### PR DESCRIPTION
**Pull request by srwiseman**
Most of the information we need is available within a JSON dump on the html page. Using a regular expression, we can isolate that JSON dump.

The other PRs only seem to address the issue of logging in. This one also addresses other exceptions I've seen (e.g. unable to auto unfollow).

### CODE REVIEW

**Comment by tolgatasci** [comment]
https://github.com/instabot-py/instabot.py/pull/1220

**Comment by srwiseman** [comment]
auto_unfollow is still broke after #1220

There are many more components still broken that rely on the URL that need to be fixed.

I'll fix more if I get time...

**Comment by rkovachev88** [comment]
This is my error after the fix. Auto unfollow is broken.

> ERROR:root:Except on auto_unfollow!
> Traceback (most recent call last):
>   File "C:\...\instabot.py-master1\src\instabot.py", line 847, in auto_unfollow
>     all_data = json.loads(re.search('{"activity.+show_app', r.text, re.DOTALL).group(0)+'":""}')['entry_data']['ProfilePage'][0]
> AttributeError: 'NoneType' object has no attribute 'group'

Is there a way to fix it?

**Comment by srwiseman** [comment]
Did you replace the url as well? It looks like the regex isn't matching
anything.

**Comment by rkovachev88** [comment]
Sorry, I'm not a coder. Which url have to be replaced?
Thank you.

**Comment by tolgatasci** [comment]
['entry_data']['ProfilePage'][0] is empty

url_user_detail = 'https://www.instagram.com/%s/?__a=1'
my change style update  #1220 
fixed next timed pulled me

**Comment by srwiseman** [comment]
Not sure who maintains this... @ChipWolf ?

**Comment by rkovachev88** [comment]
@tolgatasci I'm still getting this:

> ERROR:root:Except on auto_unfollow!
> Traceback (most recent call last):
>   File "C:\...\instabot.py-master1\src\instabot.py", line 847, in auto_unfollow
>     id_user = re.search(r',"id":"(.*?)",', r.text).group(1)
> AttributeError: 'NoneType' object has no attribute 'group'

**Comment by tolgatasci** [comment]
empty problem


id_user = re.search(r',"id":"(.*?)",', r.text).group(1)

my no problem ?
r.text null ?

**Comment by rkovachev88** [comment]
I can't understand you.

**Comment by tolgatasci** [comment]
mode = 0
my system is running. after the edits. But I showed you what you need. I guess you need to do some things. My advice is that there is no 403 error in the incoming content. my English is not good.
